added support for controlling audio devices on linux
omriharel/deej pull request #18
Opened 2020-11-02 18:51 UTC by Pieterv24

I've added support to control PA sinks directly with deej instead of only controlling individual applications

2020-11-02 21:48 UTC, omriharel reviewed
Hi @Pieterv24, looks good overall! I posted some minor comments.

In addition to the code changes, this functionality also needs to be documented properly in the README and config files (including removal of mentions of device-specific targeting being a Windows-only feature).

Please also provide users with an explanation for how they can find out the names for their audio devices (output and input), and what exactly they would need to specify to target them.

I'm also interested to know about the following:

- Can there be a conflict between device and process names? In Windows this never happens, because executables end with `.exe`
- Which OS and PA versions have you tested this with?

Thanks!

2020-11-02 21:48 UTC, omriharel commented on session_linux.go
> +type paDevice struct {
Struct name is a bit inconsistent with other session structs. I suggest using `paDeviceSession` and correspondingly renaming `paSession` -> `paProcessSession`

2020-11-02 21:48 UTC, omriharel commented on session_linux.go
> +func newPaDevice(
`newPADeviceSession` (abbreviations in name should be [all uppercase](https://github.com/golang/go/wiki/CodeReviewComments#initialisms)).

2020-11-02 21:48 UTC, omriharel commented on session_linux.go
> -		key = masterSessionName
Please simplify this logic:
```go
if isMaster {
    if isOutput {
        key = masterSessionName
    } else {
        key = inputSessionName
    }
} else {
    key = name
}

2020-11-03 18:04 UTC, Pieterv24 commented
I've updated the documentation.
As for whether it'd be possible for a conflict of device and process names to occur, technically I'd say yes although it is highly unlikely since device names are usually very unique, so someone would have to explicitly make a binary that has the same name as a output device.

There are a few courses of action we can take.
- Just leave it as is, this will most likely not cause any issues.
- Add something to check whether a session with the given key is already in the session list, if so, don't add a new one or add something like (1) to the end
- Use the Sink name instead of the Sink Description, this is more unique, but has the downside of being less human readable and less intuitive in use. for example `Built-in Audio Digital Stereo (IEC958)` would become `alsa_output.pci-0000_00_1f.3.iec958-stereo` which can only be retrieved by running `pactl list sinks` instead of being able to use the name that is used in the PulseAudio GUI.

I've tested this on Arch Linux, PulsaAudio 13.99.3 (Latest)

2020-11-03 20:32 UTC, omriharel requested changes
@Pieterv24, please see comments. Thanks!

2020-11-03 20:32 UTC, omriharel commented on README.md
> +  - Bind specific audio devices by name (on Windows and Linux (_expirimental_))
Small typo (`experimental`)

2020-11-03 20:32 UTC, omriharel commented on README.md
> +  - Linux (_expirimental_): Use the full device name, as seen in the `Output Devices` tab in `pavucontrol` or the description when running `pactl list sinks`
- Typo (same as above)
- I would prefer to distinguish the difference by writing something like:
```
Use the device's description, as seen in PulseAudio's output devices tab (or by running `pactl list sinks`)
```

2020-11-03 20:32 UTC, omriharel commented on config.yaml
> +# you can use a device's full name, i.e. "Speakers (Realtek High Definition Audio)", to bind it. this works for both output and input devices
- Please distinguish between windows and linux here as well. It doesn't need to be as thorough as the explanation in `README.md`, but it should mention that for linux it uses the device's description
- The changes to this file should be replicated to the config template file under `scripts`

2020-11-03 20:32 UTC, omriharel commented on session_linux.go
> +	// If device is the master, check if its the mic or speaker and give apporpriate default name
Typo: `appropriate`

2020-11-03 20:32 UTC, omriharel commented on session_linux.go
> +	// If device is the master, check if its the mic or speaker and give apporpriate default name
(although this is a fairly obvious `if` statement, I'm not sure it needs commenting in the first place..)

2020-11-03 20:32 UTC, omriharel commented on session_linux.go
> +type paDeviceSession struct {
Great, but what about `paSession`? Needs to be changed too for consistency

2021-03-23 01:45 UTC, fkreiner commented
Is this still a Thing?

2021-03-24 18:49 UTC, omriharel commented
@fkreiner it is, but I'm going to need to find time to bring it up to speed w/ my requirements. I keep putting it off, but I'll prioritize it higher now that there's more interest.

2021-03-25 00:42 UTC, fkreiner commented
No pressure. Just wanted to see if pulse will be implemented some day

2021-03-25 05:42 UTC, omriharel commented
Just to clarify, pulse is already supported and you can build and use deej
on Linux right now (check out the main readme for instructions).

This PR further adds to that with device targeting capabilities, which are
currently missing on Linux (being able to tell deej to control a specific
audio device like speakers or headphones, as opposed to just apps/master).

On Thu, Mar 25, 2021, 02:42 Florian Kreiner ***@***.***>
wrote:

> No pressure. Just wanted to see if pulse will be implemented some day
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/omriharel/deej/pull/18#issuecomment-806275260>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACOSGJ4BUYBFQRMXX2ECB5DTFKBGZANCNFSM4TH2QQWA>
> .
>

2021-07-01 21:15 UTC, closed without merging

2021-12-07 18:13 UTC, oerkel47 commented
This would be a nice addition! :-)